steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'horoscope-api-cloudrun'
    - '--source=.'
    - '--region=asia-northeast1'
    - '--allow-unauthenticated'
  id: Deploy
images:
- gcr.io/$PROJECT_ID/horoscope-api-cloudrun
options:
  logging: CLOUD_LOGGING_ONLY # この行が追加されました
